const express = require('express')
const {protect}= require('../middleware/auth')
 const {register,login,getMe,forgetPassword,resetPassword,updateDetails}= require('../controller/auth')
const router=express.Router()
router.route('/register').post(register)
router.route('/login').post(login)
router.route('/me').get(protect,getMe)
router.route('/updatedetails').put(protect,updateDetails)
router.route('/forgetpassword').post(forgetPassword)
router.route('/resetpassword/:resettoken').put(resetPassword)
module.exports=router